name: Format check on push
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Run dotnet format
        uses: requizm/dotnet-format@0.2.0
        with:
          action: "build"
