name: powershell

on: [push]

jobs:
    build:
      name: Run Script
      runs-on: windows-2019
      steps:
        - uses: actions/checkout@v2
        - name: Script
          run: .\scripts\*.ps1
          shell: pwsh